(function(global){'use strict';
const BUILD_TAG='20260607-inteligencia-eleitoral-picoclaw';
const V={
central:{path:'modulos/central.js',init:'centralInit',destroy:'centralDestroy',viewId:'centralView'},mapa:{path:'campo/mapa.js',init:'mapaInit',destroy:'mapaDestroy',viewId:'mapaView'},meucampo:{path:'campo/meucampo.js',init:'meucampoInit',destroy:'meucampoDestroy',viewId:'meucampoView'},percursos:{path:'campo/percursos.js',init:'percursosInit',destroy:'percursosDestroy',viewId:'percursosView'},meuinventario:{path:'campo/inventario.js',init:'inventarioInit',destroy:'inventarioDestroy',viewId:'meuinventarioView'},minhasrotas:{path:'campo/rotas.js',init:'rotasInit',destroy:'rotasDestroy',viewId:'minhasrotasView'},
dash:{path:'coordenador/dash.js',init:'dashInit',destroy:'dashDestroy',viewId:'dashView'},eleitoral:{path:'modulos/inteligencia-eleitoral-firebase.js',init:'intelInit',destroy:'intelDestroy',viewId:'eleitoralView'},operacao:{path:'modulos/operacao-territorial.js',init:'operacaoTerritorialInit',destroy:'operacaoTerritorialDestroy',viewId:'operacaoTerritorialView'},crm:{path:'modulos/crm.js',init:'crmInit',destroy:'crmDestroy',viewId:'crmView'},denuncias:{path:'modulos/denuncias.js',init:'denunciasInit',destroy:'denunciasDestroy',viewId:'denunciasView'},militantes:{path:'coordenador/equipe.js',init:'equipeInit',destroy:'equipeDestroy',viewId:'militantesView'},estoque:{path:'coordenador/estoque.js',init:'estoqueInit',destroy:'estoqueDestroy',viewId:'estoqueView'},rotas:{path:'coordenador/rotas.js',init:'rotasCoordInit',destroy:'rotasCoordDestroy',viewId:'rotasView'},
admindash:{path:'candidato/dashboard.js',init:'candDashInit',destroy:'candDashDestroy',viewId:'admindashView'},adminmapa:{path:'candidato/mapa.js',init:'candMapaInit',destroy:'candMapaDestroy',viewId:'adminmapaView'},adminagentes:{path:'candidato/agentes.js',init:'agentesInit',destroy:'agentesDestroy',viewId:'adminagentesView'},adminequipe:{path:'candidato/equipe.js',init:'candEquipeInit',destroy:'candEquipeDestroy',viewId:'adminequipeView'},logs:{path:'candidato/logs.js',init:'logsInit',destroy:'logsDestroy',viewId:'logsView'},
'master-gerador':{path:'master/gerador-picoclaw.js',init:'geradorPicoclawInit',destroy:'geradorPicoclawDestroy',viewId:'masterGeradorView'},'master-geocoding':{path:'master/geocoding-eleitoral.js',init:'geocodingEleitoralInit',destroy:'geocodingEleitoralDestroy',viewId:'masterGeocodingView'},'master-mapa-eleitoral':{path:'master/mapa-eleitoral.js',init:'mapaEleitoralInit',destroy:'mapaEleitoralDestroy',viewId:'masterMapaEleitoralView'},'master-campanhas':{path:'master/campanhas.js',init:'campanhasInit',destroy:'campanhasDestroy',viewId:'masterCampanhasView'},'master-planos':{path:'master/planos.js',init:'planosInit',destroy:'planosDestroy',viewId:'masterPlanosView'},'master-banco':{path:'master/banco-global.js',init:'bancoInit',destroy:'bancoDestroy',viewId:'masterBancoView'}};
let view=null,camp=null,mods=[],nivel=null;
const ORDEM={master:['central','master-gerador','master-geocoding','master-mapa-eleitoral','master-campanhas','master-planos','master-banco'],candidato:['central','admindash','adminmapa','operacao','adminagentes','adminequipe','dash','eleitoral','crm','denuncias','logs'],coord:['central','dash','mapa','operacao','eleitoral','crm','denuncias','militantes','estoque','rotas'],campo:['central','mapa','meucampo','percursos','meuinventario','minhasrotas','denuncias']};
const OPT={crm:['crm'],denuncias:['denuncias'],eleitoral:['eleitoral','inteligencia-eleitoral']};
function ok(id){if(!V[id])return false; if(!(ORDEM[nivel]||[]).includes(id))return false; const a=OPT[id]; return !a||mods.some(m=>a.includes(m));}
async function loadMods(){try{const cfg=await WWMX.carregarConfigCampanha(camp);mods=cfg?.modulosAtivos||[]}catch(e){mods=[]}}
function nav(){const s=document.getElementById('navSelect'); if(!s)return; const labels=WWMX.Config?.NAV_LABELS||{}; const ids=(ORDEM[nivel]||Object.keys(V)).filter(ok); s.innerHTML=ids.map(id=>`<option value="${id}">${labels[id]||id}</option>`).join(''); if(ids.length)s.value=ids[0]}
function first(){const s=document.getElementById('navSelect');return s?.value||Object.keys(V).find(ok)||'mapa'}
function src(p,r=false){return `${p}${p.includes('?')?'&':'?'}v=${encodeURIComponent(BUILD_TAG)}${r?'&r='+Date.now():''}`}
async function script(id,cfg,reload=false){const sid='script-'+id; const old=document.getElementById(sid); if(old&&!reload)return; if(old)old.remove(); await new Promise((res,rej)=>{const s=document.createElement('script');s.id=sid;s.src=src(cfg.path,reload);s.onload=res;s.onerror=()=>rej(new Error('Falha ao carregar '+cfg.path));document.head.appendChild(s)})}
async function open(id){if(!id||!V[id])return; if(!ok(id)){const f=first(); if(f&&f!==id)return open(f); return} if(view?.destroyFn){try{view.destroyFn()}catch(e){console.warn(e)}} const cfg=V[id],cont=document.getElementById('appView'); if(!cont)return; cont.innerHTML=`<div class="view active" id="${cfg.viewId}" style="display:flex;flex-direction:column;min-height:100%;"></div>`; try{await script(id,cfg,false); await new Promise(r=>setTimeout(r,10)); if(typeof global[cfg.init]!=='function'){await script(id,cfg,true); await new Promise(r=>setTimeout(r,30))}}catch(e){cont.innerHTML=`<div class="empty"><div class="empty-icon">⚠️</div>${e.message}</div>`;return} if(typeof global[cfg.init]!=='function'){cont.innerHTML=`<div class="empty"><div class="empty-icon">⚠️</div>Módulo não implementado corretamente: ${cfg.init}</div>`;return} try{global[cfg.init](camp);view={moduleId:id,destroyFn:typeof global[cfg.destroy]==='function'?global[cfg.destroy]:null,container:cont}}catch(e){console.error('[router]',e);cont.innerHTML=`<div class="empty"><div class="empty-icon">❌</div>Erro ao carregar módulo.<br><small>${e.message||''}</small></div>`}}
function init(){global.addEventListener('wwmx:session-ready',e=>{camp=e.detail.campanhaId;nivel=e.detail.nivel;loadMods().then(()=>{nav();open(global.location.hash.slice(1)||first())})});global.addEventListener('change',e=>{if(e.target.id==='navSelect'&&ok(e.target.value)){open(e.target.value);global.location.hash=e.target.value}});global.addEventListener('hashchange',()=>{const h=global.location.hash.slice(1);if(h&&ok(h)){open(h);const s=document.getElementById('navSelect');if(s)s.value=h}})}
global.WWMX=global.WWMX||{};global.WWMX.Router={init,carregarModulo:open,moduloPermitido:ok};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);
