(function(global){'use strict';
let _campanhas=[];let _selecionada=null;
function init(){render();carregar()}function destroy(){}
function render(){const c=document.getElementById('appView');if(!c)return;c.innerHTML=`<div class="dash-view"><div class="camp-hero"><div class="camp-kicker">Master · Gestão</div><div class="camp-title">Campanhas</div><div class="camp-desc">Gerencie campanhas existentes. Para criar uma nova campanha, use o Gerador PicoClaw.</div></div><button id="btnNovaCampanha" class="btn btn-primary w-full" style="margin-bottom:16px;">+ Nova campanha via Gerador PicoClaw</button><div id="masterStats" style="margin-bottom:16px;"></div><div class="section-title">Campanhas cadastradas</div><div id="listaCampanhas" class="banner-list"></div><div id="campanhaDetalhe"></div><div style="height:90px"></div></div>`;style();document.getElementById('btnNovaCampanha').onclick=irGerador}
function irGerador(){const s=document.getElementById('navSelect');if(s){s.value='master-gerador';s.dispatchEvent(new Event('change',{bubbles:true}))}else{location.hash='master-gerador'}}
async function carregar(){try{_campanhas=await WWMX.fs.getCol('campanhas')||[]}catch(e){console.warn(e);_campanhas=[]}stats();lista();if(_selecionada)detalhe(_selecionada)}
function stats(){const el=document.getElementById('masterStats');if(!el)return;const at=_campanhas.filter(c=>(c.status||'ativo')==='ativo').length;el.innerHTML=`<div class="dash-stats"><div class="stat-card total"><div class="stat-num accent">${_campanhas.length}</div><div class="stat-label">Campanhas</div></div><div class="stat-card inst"><div class="stat-num green">${at}</div><div class="stat-label">Ativas</div></div><div class="stat-card ret"><div class="stat-num red">${_campanhas.length-at}</div><div class="stat-label">Inativas</div></div></div>`}
function lista(){const el=document.getElementById('listaCampanhas');if(!el)return;if(!_campanhas.length){el.innerHTML='<div class="empty"><div class="empty-icon">🏗️</div>Nenhuma campanha criada ainda.<br>Use o Gerador PicoClaw para criar a primeira.</div>';return}el.innerHTML=_campanhas.map(c=>`<div class="banner-item" onclick="campanhasAbrirDetalhe('${escAttr(c.id)}')"><div style="width:44px;height:44px;border-radius:50%;background:linear-gradient(135deg,#98ff00,#2563eb);display:flex;align-items:center;justify-content:center;font-family:Syne,sans-serif;font-size:16px;font-weight:900;color:#07101b;flex-shrink:0;">${esc(c.numero||'?')}</div><div class="banner-info"><div class="banner-name">${esc(c.nomeExibicao||c.nomeUrna||c.candidato||c.id)}</div><div class="banner-meta">📍 ${esc(c.municipio||c.cidade||'—')}-${esc(c.uf||'')} · ${esc(c.cargo||'')} · ${esc(c.ano||'')}</div><div class="banner-meta">ID: <span style="font-family:var(--font-mono);font-size:11px;">${esc(c.id)}</span></div></div><div style="display:flex;flex-direction:column;gap:4px;align-items:flex-end;"><span class="pill ${(c.status||'ativo')==='inativo'?'pill-danger':'pill-success'}">${(c.status||'ativo')==='inativo'?'Inativa':'Ativa'}</span><span style="font-size:11px;color:var(--muted)">abrir ›</span></div></div>`).join('')}
function normalizePlano(plano){const p=String(plano||'pro').toLowerCase();if(p==='essencial')return'starter';if(p==='operacao'||p==='inteligencia')return'pro';if(p==='full')return'personalizado';return['starter','pro','elite','personalizado'].includes(p)?p:'pro'}
function planoOptions(value){const p=normalizePlano(value);return `<option value="starter" ${p==='starter'?'selected':''}>Starter</option><option value="pro" ${p==='pro'?'selected':''}>Pro</option><option value="elite" ${p==='elite'?'selected':''}>Elite</option><option value="personalizado" ${p==='personalizado'?'selected':''}>Personalizado</option>`}
async function detalhe(id){_selecionada=id;const root=document.getElementById('campanhaDetalhe');if(!root)return;const c=_campanhas.find(x=>x.id===id)||{id};let cfg={};try{cfg=await WWMX.carregarConfigCampanha(id)||{}}catch(e){}const mods=global.WWMX.Config?.MODULOS_DISPONIVEIS||[];const ativos=cfg.modulosAtivos||c.modulosAtivos||[];const senhas=cfg.senhas||{};const planoAtual=cfg.planoAssinatura||c.planoAssinatura||'pro';root.innerHTML=`<div class="camp-detail"><div style="display:flex;justify-content:space-between;gap:10px;align-items:flex-start"><div><div class="camp-kicker">Campanha selecionada</div><div class="camp-title small">${esc(c.nomeExibicao||c.nomeUrna||c.candidato||id)}</div><div class="camp-desc">${esc(id)} · ${esc(c.municipio||c.cidade||cfg.municipio||'')} ${esc(c.uf||cfg.uf||'')}</div></div><button class="btn btn-ghost" onclick="campanhasFecharDetalhe()">Fechar</button></div><div class="grid-form"><div class="field"><label>Status</label><select id="detStatus"><option value="ativo" ${(c.status||'ativo')==='ativo'?'selected':''}>Ativa</option><option value="inativo" ${(c.status||'ativo')==='inativo'?'selected':''}>Inativa</option></select></div><div class="field"><label>Plano</label><select id="detPlano">${planoOptions(planoAtual)}</select></div><div class="field"><label>Limite coordenadores</label><input id="detLimiteCoords" type="number" value="${esc(cfg.limites?.coordenadores||c.limites?.coordenadores||10)}"></div><div class="field"><label>Limite equipe campo</label><input id="detLimiteCampo" type="number" value="${esc(cfg.limites?.campo||c.limites?.campo||200)}"></div></div><div class="section-title">Senhas de acesso</div><div class="grid-form"><div class="field"><label>Campo</label><input id="detSenhaCampo" value="${esc(senhas.campo||'')}"></div><div class="field"><label>Coordenador</label><input id="detSenhaCoord" value="${esc(senhas.coord||'')}"></div><div class="field"><label>Candidato</label><input id="detSenhaCand" value="${esc(senhas.candidato||'')}"></div><div class="field"><label>Master</label><input id="detSenhaMaster" value="${esc(senhas.master||'')}"></div></div><div class="section-title">Módulos ativos</div><div class="pico-check-grid">${mods.map(m=>`<label class="pico-check"><input type="checkbox" id="detMod_${escAttr(m.id)}" ${ativos.includes(m.id)?'checked':''}> <span>${m.icon} ${esc(m.label)}</span></label>`).join('')}</div><div style="display:grid;grid-template-columns:1fr;gap:10px;margin-top:16px"><button class="btn btn-primary" onclick="campanhasSalvarDetalhe('${escAttr(id)}')">Salvar alterações</button><button class="btn btn-ghost" onclick="campanhasAbrirComoCampanha('${escAttr(id)}')">Abrir esta campanha</button></div><div id="detStatusMsg" class="camp-desc" style="margin-top:10px"></div></div>`}
async function salvar(id){try{const mods=(global.WWMX.Config?.MODULOS_DISPONIVEIS||[]).filter(m=>document.getElementById('detMod_'+m.id)?.checked).map(m=>m.id);const status=document.getElementById('detStatus').value;const plano=normalizePlano(document.getElementById('detPlano').value);const limites={coordenadores:Number(document.getElementById('detLimiteCoords').value||0),campo:Number(document.getElementById('detLimiteCampo').value||0)};const senhas={campo:document.getElementById('detSenhaCampo').value,coord:document.getElementById('detSenhaCoord').value,candidato:document.getElementById('detSenhaCand').value,master:document.getElementById('detSenhaMaster').value};await WWMX.fs.updateDoc({status,planoAssinatura:plano,modulosAtivos:mods,limites,atualizadoEm:WWMX.fs.serverTimestamp?.()||Date.now()},'campanhas',id);await WWMX.fs.setDoc({modulosAtivos:mods,senhas,planoAssinatura:plano,limites,atualizadoEm:WWMX.fs.serverTimestamp?.()||Date.now()},'campanhas',id,'config','main');WWMX.UI?.showToast?.('Campanha atualizada','success');document.getElementById('detStatusMsg').textContent='✅ Alterações salvas';carregar()}catch(e){console.error(e);WWMX.UI?.showToast?.('Erro ao salvar campanha','error')}};
function abrirCampanha(id){try{localStorage.setItem('wwmx_campanha',id)}catch(_){}location.href=location.pathname+'?c='+encodeURIComponent(id)}
function fechar(){_selecionada=null;const el=document.getElementById('campanhaDetalhe');if(el)el.innerHTML=''}
function style(){if(document.getElementById('campanhasGestaoStyle'))return;const s=document.createElement('style');s.id='campanhasGestaoStyle';s.textContent='.camp-hero,.camp-detail{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:14px;margin-bottom:14px}.camp-kicker{font-size:10px;color:var(--angel-lime,var(--accent));text-transform:uppercase;letter-spacing:1.4px;font-weight:800}.camp-title{font-family:Syne,sans-serif;font-size:26px;font-weight:900}.camp-title.small{font-size:20px}.camp-desc{font-size:12px;color:var(--muted);line-height:1.45;margin-top:4px}.grid-form,.pico-check-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-bottom:16px}.pico-check{display:flex;gap:8px;background:var(--surface2);border:1px solid var(--border);border-radius:10px;padding:10px;font-size:13px}@media(max-width:720px){.grid-form,.pico-check-grid{grid-template-columns:1fr!important}}';document.head.appendChild(s)}
function esc(v){return String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function escAttr(v){return esc(v).replace(/`/g,'')}
global.campanhasAbrirDetalhe=detalhe;global.campanhasFecharDetalhe=fechar;global.campanhasSalvarDetalhe=salvar;global.campanhasAbrirComoCampanha=abrirCampanha;global.campanhasInit=init;global.campanhasDestroy=destroy;
})(window);
