(function(global){'use strict';
let campanhaId=null, registros=[], erros=[];
const EXEMPLO=`nome,zona,secoes,eleitores,endereco,bairro,lat,lng,pct_guto,votos_guto,votos_total
EEEM NISIA FLORESTA,59,30,9366,"Rua Exemplo, Viamão RS",Centro,-30.017165,-51.022970,29.7,1965,6618
EEEM AÇORIANOS,59,23,7952,"Rua Exemplo 2, Viamão RS",Tarumã,-30.084357,-51.039468,35.6,1703,4786`;
function init(id){campanhaId=id;render();style();}
function destroy(){}
function render(){const c=document.getElementById('appView');if(!c)return;c.innerHTML=`<div class="dash-view tse-import"><div class="intel-hero"><div class="intel-kicker">PicoClaw · TSE/TRE</div><div class="intel-title">Importador de território eleitoral</div><div class="intel-desc">Cole CSV ou JSON com locais de votação. O importador normaliza, valida e grava no Firebase para a aba Eleitoral consumir.</div></div><div class="dash-stats" id="tseStats">${stat('Registros','0','accent')}${stat('Válidos','0','green')}${stat('Erros','0','yellow')}${stat('Geocod. pendente','0','purple')}</div><div class="tse-card"><div class="section-title">Entrada de dados</div><div class="grid-form"><div class="field"><label>Campanha alvo</label><input id="tseCampanhaId" value="${esc(campanhaId||'')}"></div><div class="field"><label>Formato</label><select id="tseFormato"><option value="auto">Detectar automaticamente</option><option value="csv">CSV</option><option value="json">JSON</option></select></div></div><textarea id="tseInput" class="tse-input" placeholder="Cole CSV ou JSON aqui...">${EXEMPLO}</textarea><div class="tse-actions"><button class="btn btn-primary" id="btnValidarTse">Validar</button><button class="btn btn-ghost" id="btnSalvarTse">Salvar no Firebase</button><button class="btn btn-ghost" id="btnBaixarNormalizado">Baixar normalizado</button><button class="btn btn-ghost" id="btnLimparTse">Limpar</button></div><div id="tseStatus" class="tse-status">Aguardando validação.</div></div><div class="tse-card"><div class="section-title">Preview normalizado</div><div id="tsePreview" class="tse-preview"></div></div><div class="tse-card"><div class="section-title">Pipeline PicoClaw</div><div class="intel-pre">1. coletar_zonas_secoes_locais\n2. normalizar_enderecos\n3. validar_campos_obrigatorios\n4. detectar_geocoding_pendente\n5. gravar territorios no Firebase\n6. gerar projeções iniciais\n7. abrir fila de revisão manual</div></div><div style="height:80px"></div></div>`;bind();}
function bind(){document.getElementById('btnValidarTse').onclick=validar;document.getElementById('btnSalvarTse').onclick=salvar;document.getElementById('btnBaixarNormalizado').onclick=baixar;document.getElementById('btnLimparTse').onclick=()=>{document.getElementById('tseInput').value='';registros=[];erros=[];renderPreview()}}
function parse(){const raw=document.getElementById('tseInput').value.trim(),fmt=document.getElementById('tseFormato').value;if(!raw)return[];if(fmt==='json'||(fmt==='auto'&&(raw.startsWith('[')||raw.startsWith('{')))){const data=JSON.parse(raw);return Array.isArray(data)?data:Object.values(data)}return parseCSV(raw)}
function parseCSV(raw){const lines=raw.split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const headers=splitCsv(lines[0]).map(h=>key(h));return lines.slice(1).map(line=>{const cols=splitCsv(line),o={};headers.forEach((h,i)=>o[h]=cols[i]||'');return o})}
function splitCsv(line){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===','&&!q){out.push(cur.trim());cur=''}else cur+=ch}out.push(cur.trim());return out}
function key(k){return String(k||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')}
function normalizar(r,i){const get=(...ks)=>{for(const k of ks){if(r[k]!=null&&r[k]!=='')return r[k]}return''};const id=String(get('id','codigo','cod','local_id')||slug(get('nome','local','local_votacao')+'-'+i));const nome=get('nome','local','local_votacao','nome_local');const zona=num(get('zona','ze','zona_eleitoral'));const ns=num(get('secoes','ns','total_secoes','qtd_secoes'));const el=num(get('eleitores','el','total_eleitores','aptos'));const lat=dec(get('lat','latitude'));const lng=dec(get('lng','lon','long','longitude'));const end=get('endereco','address','logradouro');const bairro=get('bairro','regiao','localidade');const votos=num(get('votos_guto','votos_historicos','votos_proprios'));const vt=num(get('votos_total','votos_validos','total_votos'))||Math.round(el*.7);const pct=dec(get('pct_guto','historico_pct','percentual_historico'))||(vt?Number((votos/vt*100).toFixed(1)):0);return{id,nome,zona,ns,el,endereco:end,bairro,lat,lng,pct_guto:pct,votos_guto:votos,votos_total:vt,geocodingStatus:(lat&&lng)?'ok':'pendente',fonte:'importador_tse_tre',importadoEm:Date.now()}}
function validar(){try{erros=[];registros=parse().map(normalizar);registros.forEach((r,i)=>{if(!r.nome)erros.push(`linha ${i+1}: nome/local ausente`);if(!r.zona)erros.push(`linha ${i+1}: zona ausente`);if(!r.el)erros.push(`linha ${i+1}: eleitores ausentes`);if(!r.lat||!r.lng)erros.push(`linha ${i+1}: geocoding pendente`) });setStatus(`Validação concluída: ${registros.length} registros, ${erros.length} alertas.`,erros.length?'warn':'ok');renderPreview()}catch(e){registros=[];erros=[e.message];setStatus('Erro ao validar: '+e.message,'error');renderPreview()}}
async function salvar(){try{if(!registros.length)validar();if(!registros.length)throw new Error('Nenhum registro válido para salvar.');const id=document.getElementById('tseCampanhaId').value.trim()||campanhaId;if(!id)throw new Error('Campanha alvo ausente.');const payload={};registros.forEach(r=>payload[r.id]=r);await WWMX.db.set(`campanhas/${id}/territorio/locais_votacao`,payload);await WWMX.db.set(`campanhas/${id}/territorio/status`,{status:'importado',total:registros.length,alertas:erros.length,geocodingPendente:registros.filter(r=>r.geocodingStatus==='pendente').length,ts:Date.now()});await WWMX.db.set(`campanhas/${id}/eleitoral/projecoes`,gerarProjecoes(registros));await WWMX.db.set(`campanhas/${id}/eleitoral/status`,{status:'projecoes_iniciais_geradas',total:registros.length,ts:Date.now()});setStatus(`✅ Importação salva em ${id}. Abra a aba Eleitoral para conferir.`, 'ok');WWMX.UI?.showToast?.('TSE/TRE importado com sucesso','success')}catch(e){console.error(e);setStatus('Erro ao salvar: '+(e.message||e),'error')}}
function gerarProjecoes(list){const out={};list.forEach(l=>{const base=l.votos_guto||Math.round((l.votos_total||l.el*.7)*(l.pct_guto||0)/100);const col=Math.round(base*1.42);out[l.id]={coligacao:{votos:col,pct:Math.min(97,Math.round(col/Math.max(l.el*.7,1)*100))},meta:{minima:Math.round(col*.92),alvo:col,ousada:Math.round(col*1.12)},prioridade:l.el>7000?'alta':l.el>5000?'media':'baixa',updatedAt:Date.now()}});return out}
function renderPreview(){const p=document.getElementById('tsePreview');if(!p)return;const geo=registros.filter(r=>r.geocodingStatus==='pendente').length;document.getElementById('tseStats').innerHTML=stat('Registros',registros.length,'accent')+stat('Válidos',Math.max(0,registros.length-erros.filter(e=>!e.includes('geocoding')).length),'green')+stat('Alertas',erros.length,'yellow')+stat('Geocod. pendente',geo,'purple');p.innerHTML=(erros.length?`<div class="tse-alerta warn"><b>Alertas</b><br>${erros.slice(0,8).map(esc).join('<br>')}${erros.length>8?'<br>...':''}</div>`:'')+`<pre class="tse-pre">${esc(JSON.stringify(registros.slice(0,20),null,2))}</pre>`}
function baixar(){if(!registros.length)validar();const b=new Blob([JSON.stringify(registros,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='locais-votacao-normalizado.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function setStatus(t,type){const el=document.getElementById('tseStatus');if(el){el.textContent=t;el.style.color=type==='error'?'var(--red)':type==='warn'?'#f59e0b':'var(--angel-lime,var(--accent))'}}
function stat(l,v,c){return`<div class="stat-card total"><div class="stat-num ${c}">${v}</div><div class="stat-label">${l}</div></div>`}function num(v){return Number(String(v||'').replace(/\./g,'').replace(',','.'))||0}function dec(v){return Number(String(v||'').replace(',','.'))||0}function slug(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,50)||('local-'+Date.now())}function esc(v){return String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function style(){if(document.getElementById('tseImportStyles'))return;const s=document.createElement('style');s.id='tseImportStyles';s.textContent='.intel-hero,.tse-card{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:14px;margin-bottom:12px}.intel-kicker{font-size:10px;color:var(--angel-lime,var(--accent));text-transform:uppercase;letter-spacing:1.4px;font-weight:800}.intel-title{font-family:Syne,sans-serif;font-size:20px;font-weight:800;margin-top:4px}.intel-desc{font-size:12px;color:var(--muted);line-height:1.45;margin-top:6px}.grid-form,.tse-actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-bottom:12px}.tse-input{width:100%;min-height:210px;background:var(--bg);border:1px solid var(--border);border-radius:var(--radius);padding:12px;color:var(--text);font-family:ui-monospace,monospace;font-size:12px}.tse-status{font-size:12px;margin-top:10px;color:var(--muted)}.tse-pre,.intel-pre{white-space:pre-wrap;background:var(--bg);border:1px solid var(--border);border-radius:8px;padding:10px;overflow:auto;max-height:380px;font-size:11px;color:var(--muted)}.tse-alerta{font-size:12px;padding:8px 12px;border-radius:8px;margin-bottom:10px}.tse-alerta.warn{background:rgba(245,158,11,.1);border:1px solid rgba(245,158,11,.3)}@media(max-width:720px){.grid-form,.tse-actions{grid-template-columns:1fr}}';document.head.appendChild(s)}
global.importadorTseInit=init;global.importadorTseDestroy=destroy;
})(window);
